apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluentd.fullname" . }}-headless
  labels:
    app: {{ template "fluentd.name" . }}
    chart: {{ template "fluentd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    # service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - name: tcp
    port: 24220
  clusterIP: None
  selector:
    app: {{ template "fluentd.name" . }}
    release: {{ .Release.Name }}
